# Generated by Django 5.0.14 on 2026-08-16 13:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase Stock In'), ('PURCHASE_RETURN', 'Purchase Return Stock Out'), ('SALE', 'Sale Stock Out'), ('SALE_RETURN', 'Sale Return Stock In'), ('ADJUSTMENT', 'Manual Stock Adjustment'), ('OPENING_STOCK', 'Initial Opening Stock')], db_index=True, max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Signed quantity (+ for in, - for out)', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction cost rate per unit', max_digits=12)),
                ('reference_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
