# Generated by Django 5.0.14 on 2026-08-16 15:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot on-hand balance after this movement', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Stock In'), ('PURCHASE_RETURN', 'Purchase Return Stock Out'), ('SALE', 'Sale Stock Out'), ('SALE_RETURN', 'Sale Return Stock In'), ('ADJUSTMENT_IN', 'Stock Adjustment In'), ('ADJUSTMENT_OUT', 'Stock Adjustment Out'), ('OPENING_STOCK', 'Initial Opening Stock')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(db_index=True, help_text='Unique adjustment identifier (e.g. ADJ-2026-00001)', max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('adjustment_type', models.CharField(choices=[('IN', 'Increase Stock (+)'), ('OUT', 'Decrease Stock (-)')], db_index=True, default='OUT', max_length=10)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged Goods'), ('LOST', 'Lost / Missing'), ('FOUND', 'Found / Discovered Stock'), ('COUNTING_ERROR', 'Counting / Physical Audit Mistake'), ('OPENING_STOCK', 'Opening Stock Entry'), ('EXPIRED', 'Expired / Spoiled'), ('OTHER', 'Other (Requires Notes)')], db_index=True, default='DAMAGED', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cost_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_stock', models.DecimalField(decimal_places=2, help_text='System on-hand stock before adjustment', max_digits=12)),
                ('actual_stock', models.DecimalField(decimal_places=2, help_text='Physical counted stock', max_digits=12)),
                ('difference_quantity', models.DecimalField(decimal_places=2, help_text='Signed adjustment quantity', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockadjustment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Adjustment Item',
                'verbose_name_plural': 'Stock Adjustment Items',
            },
        ),
    ]
