# Generated by Django 5.0.14 on 2026-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_inventory_s_product_5919a9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Stock In'), ('PURCHASE_RETURN', 'Purchase Return Stock Out'), ('SALE', 'Sale Stock Out'), ('SALE_RETURN', 'Sale Return Stock In'), ('ADJUSTMENT_IN', 'Stock Adjustment In'), ('ADJUSTMENT_OUT', 'Stock Adjustment Out'), ('OPENING_STOCK', 'Initial Opening Stock'), ('WARRANTY_REPLACEMENT', 'Warranty Replacement Stock Out'), ('WARRANTY_SUPPLIER_RECEIPT', 'Warranty Supplier Replacement Stock In')], db_index=True, max_length=30),
        ),
    ]
