# Generated by Django 5.0.14 on 2026-09-08 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Stock Adjustment', 'verbose_name_plural': 'Stock Adjustments'},
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
