# Generated by Django 5.0.14 on 2026-08-16 14:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='initial_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid upfront at checkout', max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cumulative amount paid toward this purchase', max_digits=14),
        ),
    ]
