# Generated by Django 5.0.14 on 2026-08-17 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentry_reference_type'),
        ('purchases', '0002_purchase_initial_paid_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_supplier_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Double-entry journal posting for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Reversal journal entry upon cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_supplier_payments', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], db_index=True, default='SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_supplier_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque')], db_index=True, default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_number',
            field=models.CharField(db_index=True, help_text='Unique supplier payment voucher (e.g. SUP-PAY-2026-00001)', max_length=50, unique=True),
        ),
    ]
