# Generated by Django 5.0.14 on 2026-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_supplierpayment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier_invoice_file',
            field=models.TextField(blank=True, help_text='Scanned invoice / bill document or image base64 data URL', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, db_index=True, help_text="Supplier's original invoice/bill number", max_length=100, null=True),
        ),
    ]
