# Generated by Django 5.0.14 on 2026-08-24 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentry_reference_type'),
        ('contacts', '0003_customer_opening_balance_supplier_opening_balance'),
        ('purchases', '0004_purchase_supplier_invoice_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['date', 'status'], name='purchases_p_date_e78ace_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'status'], name='purchases_p_supplie_4fc46d_idx'),
        ),
    ]
