# Generated by Django 5.0.14 on 2026-08-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentry_reference_type'),
        ('purchases', '0005_purchase_purchases_p_date_e78ace_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Receiving Cash/Bank Asset Account if refund taken in cash or bank transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='refund_method',
            field=models.CharField(choices=[('PAYABLE_DEDUCTION', 'Deduct from Supplier Payable'), ('CASH', 'Cash Refund'), ('BANK', 'Bank Transfer Refund'), ('CHEQUE', 'Cheque Refund'), ('CASH_REFUND', 'Immediate Cash / Bank Refund')], default='PAYABLE_DEDUCTION', max_length=30),
        ),
    ]
