# Generated by Django 5.0.14 on 2026-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchasereturn_payment_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cheque_bank',
            field=models.CharField(blank=True, help_text='Bank on which cheque is drawn', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Cheque issue or clearance date', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number if paid by cheque', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='cheque_bank',
            field=models.CharField(blank=True, help_text='Refund issuing bank', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Refund cheque date', null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Refund cheque number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_bank',
            field=models.CharField(blank=True, help_text='Drawn on bank name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Cheque issue / clearance date', null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank / Card'), ('CHEQUE', 'Cheque')], db_index=True, default='CASH', max_length=20),
        ),
    ]
