# Generated by Django 5.0.14 on 2026-09-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchase_cheque_bank_purchase_cheque_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Payment proof / deposit slip screenshot', null=True, upload_to='supplier_payments/'),
        ),
    ]
