# Generated by Django 5.0.14 on 2026-09-08 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_supplierpayment_screenshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Purchase Return', 'verbose_name_plural': 'Purchase Returns'},
        ),
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Supplier Payment', 'verbose_name_plural': 'Supplier Payments'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
