# Generated by Django 5.0.14 on 2026-09-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('SALE', 'Sale / Receipt'), ('SALE_RETURN', 'Sale Return / Refund'), ('PURCHASE', 'Purchase Order'), ('PURCHASE_RETURN', 'Purchase Return'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('EXPENSE', 'Operational Expense'), ('TRANSFER', 'Account Transfer'), ('CUSTOMER_PAYMENT', 'Customer Receivable Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payable Payment'), ('CUSTOMER_WARRANTY_CLAIM', 'Customer Warranty Claim'), ('SUPPLIER_WARRANTY_CLAIM', 'Supplier Warranty Claim'), ('PAYROLL', 'Payroll / Salary Accrual'), ('SALARY_PAYMENT', 'Salary Disbursement'), ('COMMISSION_ACCRUAL', 'Sales Commission Accrual'), ('COMMISSION_PAYMENT', 'Sales Commission Payment'), ('COMMISSION_REVERSAL', 'Sales Commission Reversal / Adjustment'), ('OPENING_BALANCE', 'Opening Balance'), ('REGISTER_CLOSE', 'Cash Register Close (Z-Report)'), ('MANUAL', 'Manual Journal Voucher'), ('REVERSAL', 'Reversal Counter-Entry')], db_index=True, default='MANUAL', max_length=30),
        ),
    ]
