# Generated by Django 5.0.14 on 2026-08-31 11:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_alter_journalentry_reference_type'),
        ('contacts', '0005_customerpayment_cheque_bank_and_more'),
        ('products', '0004_product_warranty_period_days'),
        ('sales', '0007_saleitem_warranty_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(db_index=True, help_text='Unique claim number (e.g. CLM-2026-00001)', max_length=50, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Claimed and replaced quantity', max_digits=12)),
                ('claim_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date the claim was filed')),
                ('warranty_expiry_date', models.DateField(blank=True, help_text='Calculated warranty expiry date at moment of claim', null=True)),
                ('original_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit cost / WAC of original product snapshot', max_digits=12)),
                ('replacement_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit cost / WAC of replacement product snapshot', max_digits=12)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='COMPLETED', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Defect description / notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_product', models.ForeignKey(help_text='Defective product returned by customer', on_delete=django.db.models.deletion.PROTECT, related_name='claimed_warranty_records', to='products.product')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_warranty_claims_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who claimed warranty', on_delete=django.db.models.deletion.PROTECT, related_name='customer_warranty_claims', to='contacts.customer')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Double-entry GL Journal Entry for this warranty transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_warranty_claims', to='accounting.journalentry')),
                ('original_sale', models.ForeignKey(help_text='Original POS Sale Invoice', on_delete=django.db.models.deletion.PROTECT, related_name='customer_warranty_claims', to='sales.sale')),
                ('replacement_product', models.ForeignKey(help_text='Replacement product issued to customer', on_delete=django.db.models.deletion.PROTECT, related_name='replacement_warranty_records', to='products.product')),
                ('sale_item', models.ForeignKey(help_text='Exact sale item line claimed', on_delete=django.db.models.deletion.PROTECT, related_name='customer_warranty_claims', to='sales.saleitem')),
                ('supplier', models.ForeignKey(help_text='Authoritative supplier responsible for this warranty claim', on_delete=django.db.models.deletion.PROTECT, related_name='customer_warranty_claims', to='contacts.supplier')),
            ],
            options={
                'verbose_name': 'Customer Warranty Claim',
                'verbose_name_plural': 'Customer Warranty Claims',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierWarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(db_index=True, help_text='Unique supplier claim batch number (e.g. SUP-CLM-2026-00001)', max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WARRANTY_COMPLETED', 'Warranty Completed (Replacement Received)'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=30)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total items in this supplier claim batch', max_digits=12)),
                ('total_valuation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost valuation of batch', max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_journal_entry', models.ForeignKey(blank=True, help_text='GL entry moving asset from Supplier Claim Asset to Inventory Asset upon receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_warranty_completions', to='accounting.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_warranty_claims_created', to=settings.AUTH_USER_MODEL)),
                ('dispatch_journal_entry', models.ForeignKey(blank=True, help_text='GL entry moving asset from Warranty Claim Asset to Supplier Claim Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_warranty_dispatches', to='accounting.journalentry')),
                ('supplier', models.ForeignKey(help_text='Supplier to whom defective items are sent', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_warranty_claims', to='contacts.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Warranty Claim',
                'verbose_name_plural': 'Supplier Warranty Claims',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierWarrantyClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valuation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('customer_warranty_claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_claim_items', to='warranty.customerwarrantyclaim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_warranty_claim_items', to='products.product')),
                ('supplier_warranty_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warranty.supplierwarrantyclaim')),
            ],
            options={
                'verbose_name': 'Supplier Warranty Claim Item',
                'verbose_name_plural': 'Supplier Warranty Claim Items',
            },
        ),
    ]
