# Generated by Django 5.0.14 on 2026-09-08 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerwarrantyclaim',
            options={'ordering': ['-claim_date', '-created_at', '-id'], 'verbose_name': 'Customer Warranty Claim', 'verbose_name_plural': 'Customer Warranty Claims'},
        ),
        migrations.AlterModelOptions(
            name='supplierwarrantyclaim',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Supplier Warranty Claim', 'verbose_name_plural': 'Supplier Warranty Claims'},
        ),
        migrations.AlterField(
            model_name='customerwarrantyclaim',
            name='claim_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Date the claim was filed'),
        ),
        migrations.AlterField(
            model_name='supplierwarrantyclaim',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
