# Generated by Django 5.0.14 on 2026-09-08 10:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Full name of sales agent', max_length=150)),
                ('code', models.CharField(db_index=True, help_text='Unique Agent Identifier Code (e.g. AGT-0001)', max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default commission percentage applied to sales (e.g. 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Commission percentage cannot be negative.'), django.core.validators.MaxValueValidator(Decimal('100.00'), message='Commission percentage cannot exceed 100%.')])),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate, help_text='Date agent joined organization')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active agents are available for new transactions; inactive agents remain accessible historically.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Agent',
                'verbose_name_plural': 'Sales Agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
