# Generated by Django 5.0.14 on 2026-09-08 11:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_journalentry_reference_type'),
        ('commission', '0001_initial'),
        ('sales', '0008_alter_sale_options_alter_salesreturn_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_number', models.CharField(db_index=True, help_text='Unique commission reference (e.g. COM-00001)', max_length=50, unique=True)),
                ('agent_name_snapshot', models.CharField(help_text='Snapshot of agent name at moment of sale', max_length=150)),
                ('agent_code_snapshot', models.CharField(help_text='Snapshot of agent code at moment of sale', max_length=50)),
                ('commission_percentage_snapshot', models.DecimalField(decimal_places=2, help_text='Snapshot of commission percentage at moment of sale', max_digits=5)),
                ('commission_base', models.DecimalField(decimal_places=2, help_text='Net commission base (Sale Subtotal - Discount Amount, excluding tax)', max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Initial calculated commission amount (Base * % / 100)', max_digits=12)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cumulative commission amount reversed due to sales returns', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cumulative amount paid out to sales agent', max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('ADJUSTED', 'Adjusted / Reversed'), ('CANCELLED', 'Cancelled')], db_index=True, default='UNPAID', max_length=25)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_commissions', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='GL journal entry for commission accrual (DR Expense / CR Payable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_accruals', to='accounting.journalentry')),
                ('sale', models.OneToOneField(help_text='Original qualifying Sale / Invoice', on_delete=django.db.models.deletion.PROTECT, related_name='commission_record', to='sales.sale')),
                ('sales_agent', models.ForeignKey(help_text='Sales agent receiving commission', on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='commission.salesagent')),
            ],
            options={
                'verbose_name': 'Commission Record',
                'verbose_name_plural': 'Commission Records',
                'ordering': ['-date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(db_index=True, help_text='Unique settlement payment voucher number (e.g. CPMT-00001)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount disbursed to sales agent', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Payment amount must be greater than zero.')])),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_payments', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='GL journal entry for payment (DR Payable / CR Cash/Bank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments', to='accounting.journalentry')),
                ('payment_account', models.ForeignKey(help_text='Cash drawer or Bank account used for disbursement', on_delete=django.db.models.deletion.PROTECT, related_name='commission_payouts', to='accounting.account')),
                ('commission_record', models.ForeignKey(help_text='Target commission record being settled', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commission.commissionrecord')),
            ],
            options={
                'verbose_name': 'Commission Payment',
                'verbose_name_plural': 'Commission Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_base_amount', models.DecimalField(decimal_places=2, help_text='Portion of commission base returned', max_digits=12)),
                ('reversal_amount', models.DecimalField(decimal_places=2, help_text='Commission amount reversed (Returned Base * Snapshotted % / 100)', max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_adjustments', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='GL journal entry for reversal (DR Payable / CR Expense)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_reversals', to='accounting.journalentry')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_adjustments', to='sales.salesreturn')),
                ('commission_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='commission.commissionrecord')),
            ],
            options={
                'verbose_name': 'Commission Adjustment',
                'verbose_name_plural': 'Commission Adjustments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['status', 'date'], name='commission__status_ee233f_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['sales_agent', 'status'], name='commission__sales_a_5c5b7d_idx'),
        ),
    ]
