# Generated by Django 5.0.14 on 2026-09-10 10:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_commissionrecord_commissionpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='commission_amount_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of commission amount unit for Progressive calculation at moment of sale', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='commission_method_snapshot',
            field=models.CharField(choices=[('FIXED_PERCENTAGE', 'Fixed Percentage'), ('PROGRESSIVE', 'Progressive / Per-Money')], db_index=True, default='FIXED_PERCENTAGE', help_text='Snapshot of commission method applied at moment of sale', max_length=25),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='effective_commission_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Calculated effective commission percentage applied to sale (e.g. 3.5000%)', max_digits=8),
        ),
        migrations.AddField(
            model_name='salesagent',
            name='commission_amount_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Money unit denominator for Progressive calculation (e.g. 100000.00 for every Rs. 100,000)', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Commission amount unit must be greater than zero.')]),
        ),
        migrations.AddField(
            model_name='salesagent',
            name='commission_method',
            field=models.CharField(choices=[('FIXED_PERCENTAGE', 'Fixed Percentage'), ('PROGRESSIVE', 'Progressive / Per-Money')], db_index=True, default='FIXED_PERCENTAGE', help_text='Commission calculation method: Fixed Percentage (Level 1) or Progressive / Per-Money (Level 2)', max_length=25),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='commission_percentage_snapshot',
            field=models.DecimalField(decimal_places=2, help_text='Snapshot of configured commission percentage at moment of sale', max_digits=5),
        ),
    ]
