# Generated by Django 5.0.14 on 2026-08-16 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPermissionRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_roles', 'Can create and modify roles and assign permissions'), ('manage_users', 'Can create, update, and toggle active status of users'), ('view_audit_logs', 'Can view system security audit logs'), ('access_pos_register', 'Can access the POS terminal screen'), ('open_cash_drawer', 'Can open cash drawer without sale'), ('close_register_z_report', 'Can perform end-of-day register closure (Z-Report)'), ('apply_custom_discount', 'Can apply manual percentage discount to sale'), ('cancel_active_sale', 'Can void or cancel an active receipt'), ('process_sale_return', 'Can process customer refunds and product returns'), ('manage_products', 'Can create, edit, and archive products'), ('view_cost_prices', 'Can view purchase cost prices of inventory'), ('create_stock_adjustment', 'Can create stock count write-offs or adjustments'), ('approve_purchases', 'Can approve supplier purchase orders'), ('view_financial_reports', 'Can access executive financial and profit reports')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('pin_code', models.CharField(blank=True, help_text='Fast POS terminal unlock PIN', max_length=6, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
