# Generated by Django 5.0.14 on 2026-08-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, default='ApexPOS Enterprise Store', help_text='Assigned company or store branch', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_scope',
            field=models.CharField(choices=[('ALL_COMPANY', 'All Company Data'), ('OWN_DATA', 'Own User / Terminal Data Only')], default='ALL_COMPANY', help_text='Data visibility boundary', max_length=50),
        ),
    ]
