# Generated by Django 5.0.14 on 2026-08-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_company_userprofile_data_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pospermissionregistry',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_roles', 'Can create and modify roles and assign permissions'), ('manage_users', 'Can create, update, and toggle active status of users'), ('view_audit_logs', 'Can view system security audit logs'), ('access_pos_register', 'Can access the POS terminal screen'), ('open_cash_drawer', 'Can open cash drawer without sale'), ('close_register_z_report', 'Can perform end-of-day register closure (Z-Report)'), ('apply_custom_discount', 'Can apply manual percentage discount to sale'), ('cancel_active_sale', 'Can void or cancel an active receipt'), ('process_sale_return', 'Can process customer refunds and product returns'), ('manage_products', 'Can create, edit, and archive products'), ('view_cost_prices', 'Can view purchase cost prices of inventory'), ('create_stock_adjustment', 'Can create stock count write-offs or adjustments'), ('view_dashboard', 'Can access the main business overview dashboard'), ('view_dashboard_analytics', 'Can view live revenue graphs, sales trends, and KPI summaries'), ('view_reports', 'Can access the business reports center'), ('view_sales_reports', 'Can view sales performance and invoice analytical reports'), ('view_inventory_reports', 'Can view stock valuation and inventory movement reports'), ('export_reports', 'Can export system data and analytical reports to Excel/PDF'), ('approve_purchases', 'Can approve supplier purchase orders'), ('view_financial_reports', 'Can access executive financial statements, profit & loss, and balance sheet'), ('view_customer_warranty_claim', 'Can view customer warranty claim records'), ('create_customer_warranty_claim', 'Can create customer warranty claim request'), ('process_customer_warranty_claim', 'Can complete customer warranty replacement and issue items'), ('view_supplier_warranty_claim', 'Can view supplier warranty claim batches'), ('create_supplier_warranty_claim', 'Can create supplier warranty claim batch'), ('process_supplier_warranty_claim', 'Can dispatch warranty claim batch to supplier (In Progress)'), ('complete_supplier_warranty_claim', 'Can receive supplier replacement stock (Warranty Completed)')]},
        ),
    ]
