# Generated by Django 5.0.14 on 2026-08-25 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('backup_type', models.CharField(choices=[('MANUAL', 'Manual Backup'), ('AUTOMATIC_DAILY', 'Daily Scheduled Backup'), ('IMPORT_RESTORE', 'Imported / Restored Backup')], default='MANUAL', max_length=30)),
                ('status', models.CharField(choices=[('LOCAL_ONLY', 'Saved Locally (.sql)'), ('DROPBOX_SYNCED', 'Saved Locally & Synced to Dropbox'), ('FAILED', 'Backup Failed'), ('RESTORED', 'Database Restored from Backup')], default='LOCAL_ONLY', max_length=30)),
                ('dropbox_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Backup Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
