# Generated by Django 5.0.14 on 2026-09-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backuplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('is_core', models.BooleanField(default=False, help_text='Core modules cannot be disabled')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Module',
                'verbose_name_plural': 'System Modules',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
