# Generated by Django 5.0.14 on 2026-08-17 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_alter_journalentry_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, help_text='Deposit slip or bank transaction ref', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], db_index=True, default='SUBMITTED', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_transfers_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(help_text='Source liquid asset account (Credit)', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.account')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Transfer journal entry (Debit To Account / Credit From Account)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='accounting.journalentry')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_transfers', to='accounting.journalentry')),
                ('to_account', models.ForeignKey(help_text='Destination liquid asset account (Debit)', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Account Transfer',
                'verbose_name_plural': 'Account Transfers',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_no', models.CharField(blank=True, help_text='Bill/Receipt/Voucher number', max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/attachments/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_expenses_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(help_text='Debit Expense Account from Chart of Accounts (e.g. Rent, Utilities)', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.account')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='General ledger entry generated upon submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.journalentry')),
                ('payment_account', models.ForeignKey(help_text='Credit Asset Account (e.g. Cash in Hand, Bank Account)', on_delete=django.db.models.deletion.PROTECT, related_name='payment_expenses', to='accounting.account')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, help_text='Reversal journal entry generated upon cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_expenses', to='accounting.journalentry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
