# Generated by Django 5.0.14 on 2026-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_expenses_ex_date_d0c7f0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cheque_bank',
            field=models.CharField(blank=True, help_text='Bank name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Cheque date', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank / Card'), ('CHEQUE', 'Cheque')], db_index=True, default='CASH', max_length=20),
        ),
    ]
