# Generated by Django 5.0.14 on 2026-09-08 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_cheque_bank_expense_cheque_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttransfer',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Account Transfer', 'verbose_name_plural': 'Account Transfers'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
