# Generated by Django 5.0.14 on 2026-08-17 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_journalentry_reference_type'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(db_index=True, help_text='Unique payment receipt number (e.g. PAY-2026-00001)', max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount reducing receivable', max_digits=14)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CARD', 'Credit / Debit Card')], db_index=True, default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Cheque # / Online Deposit Slip / POS Transaction ID', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], db_index=True, default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_customer_payments_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_payments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer making the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contacts.customer')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Double-entry journal posting for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='accounting.journalentry')),
                ('payment_account', models.ForeignKey(help_text='Debit Asset Account (e.g. Cash in Hand 1010, Bank 1020)', on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='accounting.account')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, help_text='Reversal journal entry upon cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_customer_payments', to='accounting.journalentry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_customer_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Payment',
                'verbose_name_plural': 'Customer Payments',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
