# Generated by Django 5.0.14 on 2026-08-24 11:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial/Opening receivable balance at system setup', max_digits=14),
        ),
        migrations.AddField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial/Opening payable balance at system setup', max_digits=14),
        ),
    ]
