# Generated by Django 5.0.14 on 2026-08-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_customer_opening_balance_supplier_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Payment proof / deposit slip screenshot', null=True, upload_to='customer_payments/'),
        ),
    ]
