# Generated by Django 5.0.14 on 2026-09-08 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_customerpayment_cheque_bank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customerpayment',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Customer Payment', 'verbose_name_plural': 'Customer Payments'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
