# Generated by Django 5.0.14 on 2026-08-17 10:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_alter_journalentry_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee identifier (e.g. EMP-00001)', max_length=50, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('job_title', models.CharField(db_index=True, help_text='e.g. Cashier, Store Manager, Inventory Supervisor, Sales Representative', max_length=100)),
                ('department', models.CharField(db_index=True, default='Sales & Counter Operations', help_text='e.g. Sales, Operations, Finance, Logistics', max_length=100)),
                ('date_of_joining', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Configured monthly basic wage rate (Rs.)', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_title', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status. Inactive employees retain all historical attendance and salary slips.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Optional link to system login user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_number', models.CharField(db_index=True, help_text='Unique payroll slip number (e.g. SAL-2026-00001)', max_length=50, unique=True)),
                ('month', models.PositiveSmallIntegerField(help_text='Payroll month (1-12)')),
                ('year', models.PositiveIntegerField(help_text='Payroll year (e.g. 2026)')),
                ('payroll_period', models.CharField(db_index=True, help_text='Formatted period (e.g. 2026-08)', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Issue/Calculation date')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Snapshot of base salary for this period', max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overtime, bonus, food/travel allowances', max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxes, unexcused absence/late deductions, penalties', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Final payable salary: Basic + Allowances - Deductions', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cumulative amount disbursed toward this slip', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted & Accrued'), ('PAID', 'Fully Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_salary_slips_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_slips', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_slips', to='employees.employee')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Accrual journal entry: DR 5020 Salaries Expense / CR 2030 Accrued Salaries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accrued_salary_slips', to='accounting.journalentry')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, help_text='Counter-reversal entry upon cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_salary_slips', to='accounting.journalentry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_salary_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Slip',
                'verbose_name_plural': 'Salary Slips',
                'ordering': ['-year', '-month', '-id'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(db_index=True, help_text='Unique salary payment voucher (e.g. SPAY-2026-00001)', max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Disbursement amount paid out', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Cheque # / Bank Transfer Ref', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], db_index=True, default='SUBMITTED', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_salary_disbursements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_disbursements', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='employees.employee')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Disbursement entry: DR 2030 Accrued Salaries / CR 1010 Cash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_disbursement_payments', to='accounting.journalentry')),
                ('payment_account', models.ForeignKey(help_text='Credit Asset Account (e.g. Cash in Hand 1010, Main Bank 1020)', on_delete=django.db.models.deletion.PROTECT, related_name='salary_payment_disbursements', to='accounting.account')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, help_text='Reversal journal entry upon payment cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_salary_payments', to='accounting.journalentry')),
                ('salary_slip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='employees.salaryslip')),
            ],
            options={
                'verbose_name': 'Salary Payment',
                'verbose_name_plural': 'Salary Payments',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave')], db_index=True, default='PRESENT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-id'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
