# Generated by Django 5.0.14 on 2026-08-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='cheque_bank',
            field=models.CharField(blank=True, default='', help_text='Issuing / Disbursing bank name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Cheque issuance / value date', null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='cheque_number',
            field=models.CharField(blank=True, default='', help_text='Cheque number for bank disbursement', max_length=100, null=True),
        ),
    ]
