# Generated by Django 5.0.14 on 2026-09-08 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_salarypayment_cheque_bank_salarypayment_cheque_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Salary Payment', 'verbose_name_plural': 'Salary Payments'},
        ),
        migrations.AlterModelOptions(
            name='salaryslip',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name': 'Salary Slip', 'verbose_name_plural': 'Salary Slips'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_number',
            field=models.CharField(db_index=True, help_text='Unique salary payment voucher (e.g. SALPAY-2026-00001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Issue/Calculation date'),
        ),
    ]
