# Generated by Django 5.0.14 on 2026-08-16 15:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum threshold level for low-stock alerts', max_digits=12),
        ),
    ]
