# Generated by Django 5.0.14 on 2026-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_min_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maintain_stock',
            field=models.BooleanField(db_index=True, default=True, help_text='When unchecked (Do not maintain stock), this product is stock-free/service and stock levels are not restricted.'),
        ),
    ]
