# Generated by Django 5.0.14 on 2026-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_maintain_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_period_days',
            field=models.PositiveIntegerField(blank=True, help_text='Warranty duration in days (e.g. 365 for 1 year, 180 for 6 months, null/0 for no warranty)', null=True),
        ),
    ]
