# Generated by Django 5.0.14 on 2026-09-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_warranty_period_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
