# Generated by Django 5.0.14 on 2026-08-17 11:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSDaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(db_index=True, help_text='Unique daily session serial (e.g. DAY-2026-08-17)', max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial physical cash present in drawer at opening', max_digits=12)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('opening_notes', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Expected physical cash calculated automatically from all cash-affecting transactions', max_digits=12, null=True)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Physical counted cash in drawer at closing', max_digits=12, null=True)),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between actual and expected cash (Actual - Expected)', max_digits=12, null=True)),
                ('difference_reason', models.TextField(blank=True, help_text='Explanation required if cash difference is non-zero', null=True)),
                ('closing_notes', models.TextField(blank=True, null=True)),
                ('z_report_snapshot', models.JSONField(blank=True, help_text='Immutable JSON snapshot of all final daily sales, returns, expenses, payments, and cash metrics at closing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_pos_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_pos_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Day Session',
                'verbose_name_plural': 'POS Day Sessions',
                'ordering': ['-date', '-opened_at', '-id'],
            },
        ),
    ]
