# Generated by Django 5.0.14 on 2026-08-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentry_reference_type'),
        ('sales', '0002_posdaysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Specific cash drawer or bank ledger account debited for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_payments_received', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Specific cash or bank ledger account debited for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_split_payments_received', to='accounting.account'),
        ),
    ]
