# Generated by Django 5.0.14 on 2026-08-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentry_reference_type'),
        ('sales', '0003_sale_payment_account_salepayment_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Cash drawer or bank account from which refund was paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns_paid', to='accounting.account'),
        ),
    ]
