# Generated by Django 5.0.14 on 2026-08-24 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentry_reference_type'),
        ('contacts', '0003_customer_opening_balance_supplier_opening_balance'),
        ('sales', '0004_salesreturn_payment_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at', 'status'], name='sales_sale_created_118b60_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date', 'status'], name='sales_sale_date_0a90cc_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'due_amount'], name='sales_sale_status_67159a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_by', 'status'], name='sales_sale_created_e7d1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['created_at'], name='sales_sales_created_c494d4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['created_by', 'created_at'], name='sales_sales_created_9eb346_idx'),
        ),
    ]
