# Generated by Django 5.0.14 on 2026-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_sales_sale_created_118b60_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cheque_bank',
            field=models.CharField(blank=True, help_text='Drawer / issuing bank name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Cheque issue or clearing date', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number if paid by cheque', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='cheque_bank',
            field=models.CharField(blank=True, help_text='Drawer / issuing bank name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Cheque issue or clearing date', null=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number for split cheque payment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='cheque_bank',
            field=models.CharField(blank=True, help_text='Refund issuing bank', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Refund cheque date', null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Refund cheque number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='refund_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Bank / Card'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Customer Credit / Receivable'), ('SPLIT', 'Split / Multi-Payment')], default='CASH', help_text='Payment method used to refund the customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Bank / Card'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Customer Credit / Receivable'), ('SPLIT', 'Split / Multi-Payment')], db_index=True, default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Bank / Card'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Customer Credit / Receivable'), ('SPLIT', 'Split / Multi-Payment')], max_length=20),
        ),
    ]
