# Generated by Django 5.0.14 on 2026-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_cheque_bank_sale_cheque_date_sale_cheque_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, help_text='Calculated warranty expiration date (sale.date + warranty days)', null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='warranty_period_days_snapshot',
            field=models.PositiveIntegerField(blank=True, help_text='Snapshot of product warranty duration (days) at time of sale', null=True),
        ),
    ]
