# Generated by Django 5.0.14 on 2026-09-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_commissionrecord_commissionpayment_and_more'),
        ('sales', '0008_alter_sale_options_alter_salesreturn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_agent',
            field=models.ForeignKey(blank=True, help_text='Sales agent assigned to this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='commission.salesagent'),
        ),
    ]
